# src: templates/.textlint/allowlist.yml
#  @(#) : textlint allowlist
#
# Copyright (c) 2025 atsushifx <http://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

## dict start
rules:

## end of dict
