# src: .github/workflows/ci-lint.yaml
## @(#) : ci-lint / lint new articles
#
# @version  1.0.2
# @author   Furukawa Atsushi <atsushifx@gmail.com>
# @since    2025-02-05
# @license  MIT
#
# @desc<<
#
# lint new articles on GitHub
#
#<<

name: "CI Lint Articles"

# PR及び手動でAction実行
on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.md"
  workflow_dispatch:

# 実行するAction
jobs:
  lint-on-github:
    name: lint articles on GitHub
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Fetch main repository
        run: |
          git fetch origin main

      - name: Get changed Markdown files
        id: changed-md
        run: |
          head_sha="$(git rev-parse HEAD)"
          base_sha="$(git rev-parse origin/main)"

          files=$(git diff --diff-filter=AM --name-only "${base_sha}" "${head_sha}" -- '**/*.md')
          printf "changed:\n%s\n" "$files"

          {
            echo "files<<EOF"
            echo "$files"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Setup node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          version: 10

      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          key: ${{ runner.os }}-cache
          path: |
            node_modules
            ~/.pnpm-store
            .cache/*

      - name: Install linters
        if: ${{ steps.cache-restore.outputs.cache-hit != 'true' }}
        run: |
          chmod +x ./scripts/install-doc-tools.sh
          ./scripts/install-doc-tools.sh
          pnpm list

      - name: Lint text
        if: ${{ steps.changed-md.outputs.files != '' }}
        env:
          changed_files: "${{ steps.changed-md.outputs.files }}"
        run: |
          pnpm run lint:text "${changed_files}"

      - name: Lint markdown
        if: ${{ steps.changed-md.outputs.files != '' }}
        env:
          changed_files: "${{ steps.changed-md.outputs.files }}"
        run: |
          pnpm run lint:markdown "${changed_files}"

      - name: Always save cache
        id: cache-save
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
          path: |
            node_modules
            ~/.pnpm-store
            .cache/*
