# src: .github/workflows/ci-lint.yaml
# @(#) : lint document use textlint, markdownlint
#
# Copyright (c) 2025 atsushifx <https://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT
## @(#) : ci-lint / lint new articles

name: "CI Lint Articles"

on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.md"
  workflow_dispatch:

jobs:
  lint-on-github:
    name: lint articles on GitHub
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Debug workspace
        run: |
          pwd
          ls -la
          ls -la scripts || true

      - name: Fetch main repository
        run: |
          git fetch origin main

      - name: Get changed Markdown files
        id: changed-md
        run: |
          head_sha="$(git rev-parse HEAD)"
          base_sha="$(git rev-parse origin/main)"

          files=$(git diff --diff-filter=AM --name-only "${base_sha}" "${head_sha}" -- '**/*.md')
          printf "changed:\n%s\n" "$files"

          {
            echo "files<<EOF"
            echo "$files"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10

      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          key: ${{ runner.os }}-cache
          path: |
            node_modules
            ~/.pnpm-store
            .cache/*

      - name: Install linters
        if: ${{ steps.cache-restore.outputs.cache-hit != 'true' }}
        run: |
          chmod +x ./scripts/install-doc-tools.sh
          ./scripts/install-doc-tools.sh
          pnpm list

      - name: Lint text
        if: ${{ steps.changed-md.outputs.files != '' }}
        env:
          changed_files: "${{ steps.changed-md.outputs.files }}"
        run: |
          pnpm run lint:text "${changed_files}"

      - name: Lint markdown
        if: ${{ steps.changed-md.outputs.files != '' }}
        env:
          changed_files: "${{ steps.changed-md.outputs.files }}"
        run: |
          pnpm run lint:markdown "${changed_files}"

      - name: Always save cache
        id: cache-save
        uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
          path: |
            node_modules
            ~/.pnpm-store
            .cache/*
